name: flutter_floor_exampler
description: A new Flutter project using Floor for local storage.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=3.5.0 <4.0.0"  # Aquí se especifica la versión del SDK de Dart

dependencies:
  flutter:
    sdk: flutter
  floor: ^2.2.0
  floor_annotation: ^2.2.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  floor_generator: ^2.2.0

flutter:
  uses-material-design: true
